name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BIOBASE_ACCESS_TOKEN: ${{ secrets.BIOBASE_ACCESS_TOKEN }}
      BIOBASE_PROJECT_ID: ${{ secrets.BIOBASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: biobase/setup-cli@v1
        with:
          version: latest

      - run: biobase functions deploy --project-ref $BIOBASE_PROJECT_ID