name: Deploy OG Images

on:
  push:
    branches:
      - master
    paths:
      - 'biobase/functions/og-images/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BIOBASE_ACCESS_TOKEN: ${{ secrets.BIOBASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.OG_IMAGE_BIOBASE_PROJECT_ID }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup the Biobase CLI
        uses: biobase/setup-cli@v1
        with:
          version: latest

      - run: biobase functions deploy og-images --project-ref $PROJECT_ID --no-verify-jwt
